/* This file was automatically generated by build.py */
import React from 'react'
import Article from '../javascripts/article'

const email = '<a href="&#x6d;&#x61;&#x69;&#x6c;&#x74;&#x6f;&#x3a;&#x6d;&#x76;&#x61;&#x73;&#x69;&#x6c;&#x6b;&#x6f;&#x76;&#x40;&#x67;&#x6d;&#x61;&#x69;&#x6c;&#x2e;&#x63;&#x6f;&#x6d;">&#x6d;&#x76;&#x61;&#x73;&#x69;&#x6c;&#x6b;&#x6f;&#x76;&#x40;&#x67;&#x6d;&#x61;&#x69;&#x6c;&#x2e;&#x63;&#x6f;&#x6d;</a>'

class Content extends React.Component {
    render() {
        return (
            <Article>
                <header>
                    <h1>Mark Vasilkov</h1>
                    <p>Computer programmer from Israel</p>
                </header>
                <p>I work in Python, Django, JavaScript, and React.</p>
                <p>Write to me: <span dangerouslySetInnerHTML={{ __html: email }}></span></p>
            </Article>
        )
    }
}

export default Content
